module.exports = (app) => {
  const fs = require("fs");
  const dotenv = require("dotenv");
  dotenv.config();

  const data = [
    {
      "inc_number": "INC012998172",
      "createDate": "2017-03-11T09:15:38 +06:00",
      "caller_id": 8621113101,
      "affected_user": 8621113101,
      "JobId": "f23bcd3d-a117-43b1-8312-efcc1b107af4",
      "Urgency": "Medium",
      "Category": "alerting/side jobs",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_17523462420",
      "ErrorCategory": "VNFM",
      "Comment": "Tempor aliqua sint dolor do. In commodo qui laboris non eu deserunt reprehenderit dolor dolore. Et deserunt elit ullamco ipsum in ex et magna ipsum. Ea labore excepteur elit cupidatat dolore. Aliqua esse consequat pariatur pariatur incididunt ea aliquip aliquip deserunt eu quis Lorem. Labore anim veniam dolor nisi. Duis sunt adipisicing cupidatat in mollit aliqua aliquip pariatur dolore quis.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC012731654",
      "createDate": "2020-07-02T11:43:21 +05:00",
      "caller_id": 8326225465,
      "affected_user": 8326225465,
      "JobId": "05256d77-3bd1-481b-a0ad-f15bcd981842",
      "Urgency": "Low",
      "Category": "gerneral questions",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_17309409528",
      "ErrorCategory": "API-token",
      "Comment": "Velit mollit sunt ex fugiat veniam ut adipisicing aliquip et nostrud deserunt incididunt reprehenderit exercitation. Nulla aliquip deserunt aute laborum esse minim. Sunt eiusmod veniam consequat amet. Ex ea ipsum laboris anim et veniam exercitation excepteur officia. Deserunt excepteur sunt ad nisi ut qui cillum anim officia sit sint in esse.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC012769929",
      "createDate": "2020-12-05T02:09:26 +06:00",
      "caller_id": 8450787751,
      "affected_user": 8450787751,
      "JobId": "0fee8549-fa55-4241-bee1-b09e4af7ff32",
      "Urgency": "Low",
      "Category": "enhancement request",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_13693553159",
      "ErrorCategory": "NFVD hierarchy-(DV/VDC/VNFG)",
      "Comment": "Qui qui occaecat dolore ut duis occaecat cillum deserunt. Velit Lorem nisi labore sint excepteur sunt minim aliquip. Sint excepteur in anim occaecat enim incididunt laborum eu anim minim nulla. Do ad esse id sit exercitation dolore dolor incididunt dolor esse cupidatat. Adipisicing sint sint irure pariatur sunt ullamco et eiusmod veniam irure. Laboris deserunt sint qui sunt cillum magna eu.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013260539",
      "createDate": "2018-12-14T03:34:42 +06:00",
      "caller_id": 8723281150,
      "affected_user": 8723281150,
      "JobId": "f1364e93-36c8-4365-93cc-88518627ef2d",
      "Urgency": "Low",
      "Category": "gerneral questions",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_14447924642",
      "ErrorCategory": "API-token",
      "Comment": "Occaecat duis commodo aute est. Do esse veniam cupidatat veniam minim sint adipisicing magna nisi incididunt et mollit. Pariatur ad nisi enim laborum.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC013499193",
      "createDate": "2016-11-07T08:32:54 +06:00",
      "caller_id": 8617431507,
      "affected_user": 8617431507,
      "JobId": "ac172075-732e-4116-bacc-38539e287afb",
      "Urgency": "High",
      "Category": "gerneral questions",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_17828286020",
      "ErrorCategory": "VNFM",
      "Comment": "Qui voluptate sunt qui pariatur cupidatat pariatur do amet qui consequat ullamco pariatur voluptate. Dolore commodo excepteur id sint sit non labore nulla in aute. Laborum do cupidatat consequat ad. Elit duis deserunt id proident dolore.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC013194680",
      "createDate": "2014-03-11T10:01:43 +05:00",
      "caller_id": 8780051692,
      "affected_user": 8780051692,
      "JobId": "a52bebdc-17c8-4590-b7e2-8f263f1ef03a",
      "Urgency": "Low",
      "Category": "atlas issues",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_17639377288",
      "ErrorCategory": "NFVD Access-New acct",
      "Comment": "Laborum anim dolor Lorem ullamco. Nisi sit est Lorem anim anim ipsum. In reprehenderit ipsum id aliquip tempor ex aute ut elit aliquip consectetur officia tempor. Minim veniam proident dolore aliquip cupidatat proident excepteur nulla. Dolore non adipisicing Lorem id irure irure occaecat nulla fugiat nulla sunt est nulla.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC012618919",
      "createDate": "2022-09-14T04:43:37 +05:00",
      "caller_id": 8706884346,
      "affected_user": 8706884346,
      "JobId": "c9e35c9c-ec38-4e76-9872-3b752de8ba55",
      "Urgency": "Low",
      "Category": "other",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_14155999360",
      "ErrorCategory": "NFVD UI",
      "Comment": "Ea consectetur culpa consectetur esse est. Occaecat officia eu eiusmod ad dolor ea in. Labore esse occaecat excepteur consequat eiusmod est cupidatat ullamco cupidatat cupidatat proident sunt anim. Quis elit adipisicing ea Lorem fugiat commodo. Labore ea incididunt cillum dolor eu commodo amet.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC012167287",
      "createDate": "2017-06-06T02:24:53 +05:00",
      "caller_id": 8948117862,
      "affected_user": 8948117862,
      "JobId": "cef5ed79-7061-4e7f-8f44-238421f4e1f9",
      "Urgency": "High",
      "Category": "onboarding issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_17828886374",
      "ErrorCategory": "CNF Deploy/Upgrade Issue",
      "Comment": "Velit consequat fugiat consectetur consequat esse ad incididunt tempor elit esse adipisicing sunt est aliqua. Cupidatat sunt dolor cillum consequat pariatur. Culpa ea sunt eu cupidatat anim ad.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC012713772",
      "createDate": "2014-02-12T09:24:09 +06:00",
      "caller_id": 8633462302,
      "affected_user": 8633462302,
      "JobId": "2d18a23b-b02e-421d-9cfb-4483138e4704",
      "Urgency": "Medium",
      "Category": "vmfmp issues",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_16066515524",
      "ErrorCategory": "CNF Deploy/Upgrade Issue",
      "Comment": "Magna culpa incididunt irure aliquip occaecat velit aliqua. Pariatur adipisicing magna minim anim ea irure irure et cillum laborum labore. Minim cillum fugiat eu culpa fugiat voluptate commodo pariatur est deserunt do do. Ut adipisicing sunt aute mollit fugiat excepteur non non fugiat anim eiusmod amet aliqua esse.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC013202919",
      "createDate": "2018-03-21T06:49:11 +05:00",
      "caller_id": 8482566913,
      "affected_user": 8482566913,
      "JobId": "e35dbb3f-f8b3-4955-9da4-a2f94dfd133c",
      "Urgency": "Low",
      "Category": "alerting/side jobs",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_17186273872",
      "ErrorCategory": "VNFM",
      "Comment": "Occaecat ullamco incididunt nisi tempor enim consectetur. Nulla amet deserunt magna dolore nostrud. Culpa esse occaecat id commodo esse enim ex adipisicing nulla in id laboris velit eu. Proident cillum pariatur commodo anim labore ut dolore do labore aute pariatur consectetur incididunt deserunt. Proident commodo ut officia dolor dolore veniam in. Dolor duis mollit sint dolore pariatur cupidatat ex. Do Lorem ex sunt voluptate incididunt dolore id exercitation.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013440624",
      "createDate": "2023-08-19T12:24:36 +05:00",
      "caller_id": 8336169927,
      "affected_user": 8336169927,
      "JobId": "f54467ee-f878-4707-8e0d-7a2d5ced7111",
      "Urgency": "Low",
      "Category": "gerneral questions",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_14473489059",
      "ErrorCategory": "API-token",
      "Comment": "Deserunt esse mollit eiusmod dolore. Commodo quis sit irure labore. Ullamco id quis culpa culpa irure dolor esse. Id Lorem reprehenderit officia cillum et fugiat minim. Id dolor fugiat dolore exercitation nisi amet. Laborum in eu aute ad aliqua adipisicing officia cupidatat Lorem excepteur ea culpa.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC013707242",
      "createDate": "2023-02-17T10:41:34 +06:00",
      "caller_id": 8135198890,
      "affected_user": 8135198890,
      "JobId": "69564508-4dca-4778-9512-bbf5fe9d036e",
      "Urgency": "Low",
      "Category": "alerting/side jobs",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_16114844826",
      "ErrorCategory": "NFVD UI",
      "Comment": "Sint deserunt sit et cupidatat id commodo nostrud ea ad ea Lorem proident elit. Anim commodo ut ut minim quis commodo dolore tempor irure esse esse proident labore velit. Et ullamco veniam ea ad reprehenderit cupidatat quis nulla ex laboris occaecat. Aute fugiat do dolor exercitation velit sit Lorem nostrud et sunt aliquip aliquip quis cupidatat. Dolore minim amet ad reprehenderit aliqua veniam non dolore ipsum aute exercitation sit ex qui.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC012295498",
      "createDate": "2021-09-27T12:17:13 +05:00",
      "caller_id": 8404800704,
      "affected_user": 8404800704,
      "JobId": "14c15650-3cc1-4b72-9510-15167c818415",
      "Urgency": "High",
      "Category": "vmfmp issues",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_16656800145",
      "ErrorCategory": "VNFM",
      "Comment": "Eiusmod pariatur deserunt ea nostrud nostrud fugiat cupidatat. Id eiusmod laborum ipsum cillum ullamco laboris culpa. Consequat velit nisi enim amet sit exercitation ex culpa nisi pariatur non. Ullamco occaecat nostrud commodo exercitation adipisicing quis officia sint ad quis mollit sunt officia tempor. Velit eiusmod proident culpa amet excepteur ex ullamco id fugiat aute ullamco.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC013944278",
      "createDate": "2021-09-13T06:10:07 +05:00",
      "caller_id": 8680835062,
      "affected_user": 8680835062,
      "JobId": "7ee0dd71-324d-40e1-8c44-627d2baa99d1",
      "Urgency": "Medium",
      "Category": "vmfmp issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_16457897771",
      "ErrorCategory": "Onboarding-Kubeconfig connectivity",
      "Comment": "Adipisicing qui non tempor cillum proident excepteur ea ut veniam nostrud nulla reprehenderit nulla. Ea cillum et ut id est magna irure dolore tempor incididunt velit Lorem. Minim elit dolore enim reprehenderit. Deserunt dolore deserunt consequat est excepteur do do.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC012288382",
      "createDate": "2022-08-27T12:01:20 +05:00",
      "caller_id": 8525845884,
      "affected_user": 8525845884,
      "JobId": "a232a925-54fb-45be-afc7-1efdfb8514f3",
      "Urgency": "Medium",
      "Category": "enhancement request",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_15160703649",
      "ErrorCategory": "NFVD UI",
      "Comment": "Irure nostrud ea aute ad ex dolor laborum veniam velit velit. Esse do officia laborum aliquip. Qui cillum veniam adipisicing in culpa enim ipsum mollit ex duis officia veniam sit nostrud. Amet id nostrud voluptate eu nulla enim adipisicing. Exercitation eiusmod enim ipsum enim eiusmod aliqua sit ad.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC013041073",
      "createDate": "2024-06-19T11:51:32 +05:00",
      "caller_id": 8680677823,
      "affected_user": 8680677823,
      "JobId": "4953cc05-a2a5-49c9-81d1-25713951fcba",
      "Urgency": "High",
      "Category": "onboarding issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_18443721840",
      "ErrorCategory": "VNF Deploy/Upgrade Issue",
      "Comment": "Pariatur sunt ullamco ipsum tempor ipsum irure amet cupidatat consequat dolore commodo cillum minim laborum. Est laborum sit nostrud consectetur ex. Aute minim consequat aliquip enim sit Lorem. Occaecat laborum ullamco voluptate qui magna laboris laboris qui. Aute sunt laboris sit non eu ullamco ex reprehenderit anim velit amet excepteur. Labore laboris ex veniam magna dolore sunt sunt irure id ullamco non id enim voluptate. Enim eu commodo aute consequat cillum voluptate ex occaecat.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC013823055",
      "createDate": "2024-03-20T08:41:26 +05:00",
      "caller_id": 8178704395,
      "affected_user": 8178704395,
      "JobId": "cca63e22-77e5-4748-9f16-79949fb297ae",
      "Urgency": "Low",
      "Category": "NFVD gui issues",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_18431767741",
      "ErrorCategory": "NFVD UI",
      "Comment": "Sint qui est ut nisi. Deserunt velit eiusmod do proident amet veniam in ea. Qui aliquip deserunt labore aute ipsum occaecat et nostrud. Amet eu excepteur pariatur eiusmod labore irure dolor sit amet reprehenderit Lorem. Et laborum nulla tempor dolore nisi Lorem eu. Ex cillum labore fugiat adipisicing nisi culpa culpa occaecat sint labore ullamco sit. Consequat cupidatat consequat Lorem tempor aliqua.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC013000869",
      "createDate": "2014-07-13T02:48:52 +05:00",
      "caller_id": 8618091215,
      "affected_user": 8618091215,
      "JobId": "0a7fcc0b-9455-4c31-a694-37208857f0d7",
      "Urgency": "Low",
      "Category": "alerting/side jobs",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_16511058138",
      "ErrorCategory": "Error executing operation deploy",
      "Comment": "Tempor elit sunt sunt ut proident. Culpa aliquip exercitation aliqua ea qui ex ipsum. Tempor deserunt magna pariatur culpa voluptate ut culpa aliqua ad pariatur mollit ea veniam cupidatat. Id esse qui ex eiusmod eiusmod tempor reprehenderit aliquip elit excepteur voluptate. Aute irure dolore Lorem ipsum duis in et. Veniam nisi enim ex nostrud sunt.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC012974744",
      "createDate": "2023-01-11T10:21:52 +06:00",
      "caller_id": 8911751044,
      "affected_user": 8911751044,
      "JobId": "6f4010d0-17f5-4dd3-b52a-817757b64325",
      "Urgency": "Medium",
      "Category": "other",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_14318928558",
      "ErrorCategory": "Error executing operation deploy",
      "Comment": "Ex cillum enim sit fugiat deserunt aliquip aliquip velit do. Aute voluptate labore eiusmod incididunt. Commodo ut amet adipisicing adipisicing qui in cillum nulla dolore duis labore cillum veniam. Officia minim do laborum dolor est nostrud fugiat consectetur. Laborum velit irure aute nisi adipisicing consequat laborum do mollit cillum incididunt veniam mollit eiusmod. Ea ea aute esse sint. Voluptate fugiat mollit anim aliquip excepteur velit occaecat cillum ipsum.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC012394418",
      "createDate": "2017-11-25T05:38:34 +06:00",
      "caller_id": 8278338358,
      "affected_user": 8278338358,
      "JobId": "bc1f1871-d463-4e87-a519-bd55c5b9c38c",
      "Urgency": "Medium",
      "Category": "alerting/side jobs",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_14474790496",
      "ErrorCategory": "Error executing operation deploy",
      "Comment": "Velit ut qui mollit non pariatur occaecat veniam occaecat magna ea adipisicing culpa. Dolor exercitation deserunt cillum culpa nisi. Esse exercitation proident sint nisi cupidatat veniam veniam cillum cillum anim cillum eiusmod veniam ea. Laborum id dolore minim mollit sunt quis adipisicing sit voluptate dolor Lorem proident cillum nisi.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC013135844",
      "createDate": "2023-02-03T09:27:56 +06:00",
      "caller_id": 8328859153,
      "affected_user": 8328859153,
      "JobId": "d0a781a8-66f9-4946-a8b0-ab38c5ef1798",
      "Urgency": "Low",
      "Category": "gerneral questions",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_17716219818",
      "ErrorCategory": "NFVD Access-New acct",
      "Comment": "Deserunt magna labore in enim reprehenderit minim eiusmod irure. Irure reprehenderit tempor in in dolor culpa excepteur irure eiusmod deserunt consequat. Qui ex eu excepteur proident duis quis do cupidatat qui duis aute ex eu.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC012599357",
      "createDate": "2017-09-29T01:21:43 +05:00",
      "caller_id": 8822782004,
      "affected_user": 8822782004,
      "JobId": "af8944d7-4cf1-4bf0-a790-3f2d43bf6e61",
      "Urgency": "Medium",
      "Category": "enhancement request",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_16446314458",
      "ErrorCategory": "API-token",
      "Comment": "Ea id sunt sit nisi laborum dolor. Lorem amet pariatur aliqua aliquip irure commodo et non aute laboris in eu dolor velit. Irure Lorem id sint laboris Lorem.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC012613337",
      "createDate": "2015-01-26T06:24:54 +06:00",
      "caller_id": 8835455562,
      "affected_user": 8835455562,
      "JobId": "31571ce8-b2cd-4efa-9c3a-204a7df9e1e0",
      "Urgency": "High",
      "Category": "enhancement request",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_17041008825",
      "ErrorCategory": "CNF Deploy/Upgrade Issue",
      "Comment": "Esse magna sint sit consequat. Sint esse ex qui ea eiusmod dolore occaecat. Laborum voluptate ad reprehenderit veniam aute eu consequat et laborum ipsum. Nostrud aliqua voluptate qui consectetur Lorem aliqua cillum ex veniam proident dolore et. Adipisicing voluptate nostrud ipsum fugiat commodo cillum eiusmod in sint sit ad commodo sit.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC012578432",
      "createDate": "2023-08-07T09:43:46 +05:00",
      "caller_id": 8298159830,
      "affected_user": 8298159830,
      "JobId": "a53d6b46-92d6-4ee1-8592-7ccea598813f",
      "Urgency": "High",
      "Category": "gerneral questions",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_17074881202",
      "ErrorCategory": "Error executing operation deploy",
      "Comment": "Consectetur excepteur cupidatat mollit do consectetur qui tempor ad sit anim eiusmod. Et cupidatat exercitation do voluptate cupidatat ut nostrud dolor eiusmod magna occaecat voluptate duis. Exercitation cillum elit irure dolore consectetur. Ullamco sit minim minim reprehenderit minim laboris. Sit amet id laborum labore excepteur id dolor. Et elit non ex dolor irure eu laborum culpa proident veniam sint. Commodo irure nostrud reprehenderit nulla aliquip.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013266839",
      "createDate": "2020-04-11T04:34:38 +05:00",
      "caller_id": 8650532208,
      "affected_user": 8650532208,
      "JobId": "2a0986c7-cdf2-4179-9c59-bb3855742ca8",
      "Urgency": "Low",
      "Category": "vmfmp issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_17416973488",
      "ErrorCategory": "NFVD UI",
      "Comment": "Labore magna anim laborum do voluptate qui. Aute cupidatat proident excepteur pariatur veniam veniam ipsum velit est consectetur in aliquip id dolore. Sit mollit aliquip irure dolore adipisicing aliqua proident magna exercitation aliqua consequat mollit sint quis.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC013287025",
      "createDate": "2018-03-14T02:51:05 +05:00",
      "caller_id": 8735991246,
      "affected_user": 8735991246,
      "JobId": "288a65de-3dfa-4e5a-a8b2-02223984147e",
      "Urgency": "Low",
      "Category": "NFVD portal issues",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_16274974142",
      "ErrorCategory": "VNF Deploy/Upgrade Issue",
      "Comment": "Pariatur duis minim culpa officia magna laborum irure aute in. Fugiat proident adipisicing exercitation velit ipsum elit ad laborum eiusmod deserunt pariatur ad qui deserunt. Et sunt in sint proident proident cupidatat incididunt exercitation esse Lorem.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013004306",
      "createDate": "2018-11-21T09:45:49 +06:00",
      "caller_id": 8579218555,
      "affected_user": 8579218555,
      "JobId": "76545f1a-81a3-456a-bdf6-a5541fc70344",
      "Urgency": "High",
      "Category": "onboarding issues",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_15477709424",
      "ErrorCategory": "CNF Deploy/Upgrade Issue",
      "Comment": "Amet ad ex ut tempor minim ex consectetur consectetur deserunt pariatur Lorem mollit voluptate. Cupidatat exercitation nostrud mollit occaecat et ullamco labore ut occaecat ea. Nostrud dolor quis occaecat ullamco nulla nostrud duis. Do velit ea quis minim fugiat Lorem fugiat. Sunt in culpa pariatur ex.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC012413009",
      "createDate": "2015-06-01T05:54:57 +05:00",
      "caller_id": 8811159360,
      "affected_user": 8811159360,
      "JobId": "f2ee578e-d5be-4e74-a6bb-c182330b83bb",
      "Urgency": "High",
      "Category": "other",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_13722653627",
      "ErrorCategory": "CNF Deploy/Upgrade Issue",
      "Comment": "Qui nisi ad nulla excepteur elit voluptate. Adipisicing irure Lorem aliqua cillum mollit tempor aute tempor non laborum voluptate. Consectetur excepteur laborum consectetur irure culpa minim do aute duis id consequat excepteur.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013860975",
      "createDate": "2023-04-30T07:04:22 +05:00",
      "caller_id": 8773250853,
      "affected_user": 8773250853,
      "JobId": "d2df4cc9-bfa7-4695-a284-d63918106455",
      "Urgency": "High",
      "Category": "alerting/side jobs",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_14856088636",
      "ErrorCategory": "Error executing operation deploy",
      "Comment": "Do in aliquip voluptate incididunt id dolor non sunt ipsum consequat cillum cillum voluptate. Deserunt magna adipisicing voluptate deserunt id officia consectetur eu aute dolor labore Lorem. Consequat aliquip pariatur excepteur proident excepteur deserunt labore. Ex id fugiat est nisi occaecat amet ipsum id ipsum nulla veniam velit pariatur reprehenderit.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC012371499",
      "createDate": "2021-12-21T04:08:16 +06:00",
      "caller_id": 8275879192,
      "affected_user": 8275879192,
      "JobId": "15e706d3-1815-4039-bb9b-24efd46e2c55",
      "Urgency": "Medium",
      "Category": "atlas issues",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_15702039700",
      "ErrorCategory": "NFVD Access-New acct",
      "Comment": "Elit dolore laborum aute ipsum duis voluptate laborum sit ut aliquip irure id. Adipisicing anim amet mollit incididunt id sint labore irure aliqua fugiat fugiat. Quis commodo commodo et sit sint Lorem elit duis enim eu deserunt ullamco. Ea aliquip consectetur reprehenderit culpa eiusmod voluptate.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC013591322",
      "createDate": "2019-12-24T03:33:04 +06:00",
      "caller_id": 8415448914,
      "affected_user": 8415448914,
      "JobId": "8e66183f-b8f8-44a6-82c9-24955385046d",
      "Urgency": "Low",
      "Category": "onboarding issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_17523931118",
      "ErrorCategory": "NFVD Access-New acct",
      "Comment": "Nulla pariatur sint occaecat id nisi sint. Sint culpa dolore ullamco eu minim non non nulla do qui. Ipsum fugiat officia voluptate minim laboris sint duis aute adipisicing. Laborum ad mollit enim commodo. Ut deserunt non proident fugiat excepteur proident Lorem quis esse aliquip minim incididunt qui mollit. Minim adipisicing dolore tempor id culpa. Anim minim labore officia magna.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC012504699",
      "createDate": "2015-03-22T09:22:24 +05:00",
      "caller_id": 8247019743,
      "affected_user": 8247019743,
      "JobId": "465f5ac6-8e28-4c30-bf23-88c1b6cd289c",
      "Urgency": "Medium",
      "Category": "vmfmp issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_15167505998",
      "ErrorCategory": "CNF Deploy/Upgrade Issue",
      "Comment": "Sunt cupidatat ex sunt veniam mollit. Esse culpa minim irure ea cupidatat velit cupidatat enim elit nisi ex Lorem. Veniam eu sit elit et dolore ex. Magna et sint duis ullamco tempor commodo. Mollit esse culpa aute eiusmod dolor sunt laboris voluptate aliquip dolore commodo reprehenderit. Ullamco fugiat esse aliqua veniam non deserunt dolore non reprehenderit veniam elit dolore dolor esse. Aliquip exercitation magna eiusmod dolor sunt culpa mollit est esse voluptate excepteur ea exercitation laborum.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC012385477",
      "createDate": "2024-04-30T04:12:56 +05:00",
      "caller_id": 8688285381,
      "affected_user": 8688285381,
      "JobId": "f29fede6-c2c7-4c85-87e8-4a1bcb48f997",
      "Urgency": "Low",
      "Category": "NFVD portal issues",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_17995252792",
      "ErrorCategory": "Error executing operation deploy",
      "Comment": "Non laborum aliqua occaecat elit labore irure magna minim officia. Dolor ad nisi ea commodo deserunt reprehenderit elit qui nulla elit veniam. Reprehenderit amet non Lorem velit et deserunt pariatur. Ut et non veniam in officia laboris reprehenderit. Ad minim quis magna eu. Laboris aliquip dolor ut et Lorem quis occaecat aliqua qui consectetur ex consequat ea in. Mollit culpa Lorem cillum et deserunt veniam occaecat.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC013089890",
      "createDate": "2021-09-17T02:19:57 +05:00",
      "caller_id": 8854562379,
      "affected_user": 8854562379,
      "JobId": "80be2e2b-54f3-40e0-bfb2-c841258eab26",
      "Urgency": "High",
      "Category": "gerneral questions",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_15387122842",
      "ErrorCategory": "Error executing operation deploy",
      "Comment": "Ad magna id sint mollit. Esse occaecat sunt cupidatat nulla consectetur. Cillum mollit culpa reprehenderit nostrud dolor. Do elit ea aliqua esse nisi veniam. Nisi eiusmod ex aliquip magna esse aliquip dolore duis do est non magna minim sint. Laboris eiusmod aliquip ipsum fugiat consectetur mollit veniam. Adipisicing aute irure adipisicing cupidatat sunt consequat fugiat deserunt occaecat aliqua.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC013193930",
      "createDate": "2021-08-03T12:46:53 +05:00",
      "caller_id": 8685774561,
      "affected_user": 8685774561,
      "JobId": "a8f717a5-b78e-4f94-8f30-888cd8897f04",
      "Urgency": "High",
      "Category": "atlas issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_14918970248",
      "ErrorCategory": "VNFM",
      "Comment": "Duis et occaecat excepteur anim irure nulla velit nostrud esse quis occaecat esse ipsum. Sunt culpa sit ipsum magna exercitation. Nisi duis Lorem sunt amet in nostrud proident quis aute voluptate duis occaecat dolore nisi. Labore deserunt nulla ipsum irure aute cupidatat et sunt sunt.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC013931296",
      "createDate": "2020-09-16T05:56:22 +05:00",
      "caller_id": 8389439954,
      "affected_user": 8389439954,
      "JobId": "34f6e353-9fc7-43c8-8e70-c960c9d8ce88",
      "Urgency": "Low",
      "Category": "onboarding issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_15441176193",
      "ErrorCategory": "NFVD hierarchy-(DV/VDC/VNFG)",
      "Comment": "Sit nostrud deserunt sunt quis nulla consectetur non fugiat. Officia consequat quis occaecat deserunt labore deserunt voluptate ipsum velit officia esse labore. Dolor exercitation nisi cupidatat est et occaecat pariatur laborum ut voluptate mollit. Minim commodo fugiat sunt qui consequat anim laboris irure aliquip id.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC012787462",
      "createDate": "2015-01-25T02:14:49 +06:00",
      "caller_id": 8789391749,
      "affected_user": 8789391749,
      "JobId": "c6ff0ef6-7319-4045-89fa-18651c9a0efe",
      "Urgency": "Medium",
      "Category": "gerneral questions",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_15840972265",
      "ErrorCategory": "CNF Deploy/Upgrade Issue",
      "Comment": "Commodo ipsum mollit enim consectetur consequat magna. Nostrud ex laborum ullamco esse dolore consectetur anim occaecat cupidatat do ad. Consequat non duis minim incididunt aute labore esse anim dolor ut proident qui. Tempor reprehenderit esse enim laboris fugiat aliqua officia. Adipisicing aute do labore consequat consequat id do irure irure minim aute proident irure in. Voluptate magna cillum aliqua occaecat pariatur amet velit ullamco magna non labore commodo deserunt.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC014082390",
      "createDate": "2020-04-30T04:14:33 +05:00",
      "caller_id": 8422571700,
      "affected_user": 8422571700,
      "JobId": "d1490660-7ed3-47bd-a5c6-f13311c128fe",
      "Urgency": "High",
      "Category": "gerneral questions",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_18480273392",
      "ErrorCategory": "Error executing operation deploy",
      "Comment": "Veniam aute incididunt cillum do cupidatat adipisicing esse eiusmod enim et quis qui proident. Sunt nulla fugiat enim veniam magna id esse est aliquip amet elit culpa veniam minim. Sit exercitation non veniam id ea.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC012372781",
      "createDate": "2022-07-28T01:22:19 +05:00",
      "caller_id": 8483842353,
      "affected_user": 8483842353,
      "JobId": "dc14b42f-277e-4004-bd38-629c513bb685",
      "Urgency": "Medium",
      "Category": "onboarding issues",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_16895778634",
      "ErrorCategory": "VNFM",
      "Comment": "Non Lorem adipisicing quis dolore elit ipsum. Excepteur dolor commodo ipsum mollit officia anim. Qui eiusmod irure labore esse commodo fugiat non et. Magna ad reprehenderit cillum exercitation sit est. Esse sunt dolor occaecat est fugiat non fugiat enim adipisicing elit adipisicing. Quis deserunt reprehenderit nisi non ipsum aute amet.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC012507321",
      "createDate": "2015-06-27T08:33:58 +05:00",
      "caller_id": 8837393882,
      "affected_user": 8837393882,
      "JobId": "9a8bf90a-bec1-4402-b241-fdfdd7770ab3",
      "Urgency": "Low",
      "Category": "alerting/side jobs",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_18092435296",
      "ErrorCategory": "VNF Deploy/Upgrade Issue",
      "Comment": "Exercitation ut fugiat exercitation non eu tempor nisi dolor aute incididunt reprehenderit. Do excepteur ut fugiat consectetur irure. Incididunt cillum quis exercitation ea esse nostrud proident est ut reprehenderit culpa. Qui fugiat mollit anim enim labore do ex in in enim id amet. Ullamco qui eiusmod eu incididunt aliquip excepteur cillum laboris occaecat magna occaecat.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC012489067",
      "createDate": "2019-05-31T01:11:52 +05:00",
      "caller_id": 8908474362,
      "affected_user": 8908474362,
      "JobId": "26a9c790-9516-4475-851e-3f485db43df6",
      "Urgency": "Low",
      "Category": "atlas issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_16511539263",
      "ErrorCategory": "API-token",
      "Comment": "Eiusmod dolor enim aliquip do est qui enim et eu elit. Cupidatat anim labore officia tempor magna excepteur mollit fugiat mollit excepteur ipsum velit do. Nulla non commodo sunt mollit nostrud elit veniam sit reprehenderit. Duis voluptate aliqua eu reprehenderit tempor mollit dolore et et elit commodo mollit. Enim non aliquip anim anim. Voluptate mollit anim deserunt ea nostrud nostrud consequat ut ut esse consequat.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC012596441",
      "createDate": "2024-06-08T12:08:13 +05:00",
      "caller_id": 8828757212,
      "affected_user": 8828757212,
      "JobId": "1994b215-4677-414b-a7a6-453984036263",
      "Urgency": "High",
      "Category": "atlas issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_15989268307",
      "ErrorCategory": "NFVD Access-New acct",
      "Comment": "Excepteur ut duis proident consectetur. Id anim laborum anim nisi in. Tempor velit labore cupidatat irure eu laborum fugiat Lorem qui anim. Nostrud esse adipisicing esse nisi ex ullamco ut fugiat sit laboris sit aute. Qui adipisicing ipsum sunt et nulla ipsum est consectetur exercitation non.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013677943",
      "createDate": "2017-10-20T05:01:05 +05:00",
      "caller_id": 8912867228,
      "affected_user": 8912867228,
      "JobId": "e3ce49c5-3203-442f-a08a-44343c6505b6",
      "Urgency": "High",
      "Category": "gerneral questions",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_15054877694",
      "ErrorCategory": "VNFM",
      "Comment": "Aliqua consectetur non do et incididunt commodo id magna. Velit excepteur ex enim in ea amet magna Lorem est et consectetur. Anim exercitation aliquip exercitation commodo laboris dolore aliqua proident anim irure laboris amet duis.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC013683660",
      "createDate": "2018-12-17T01:40:27 +06:00",
      "caller_id": 8355278869,
      "affected_user": 8355278869,
      "JobId": "a90d7b3f-dce0-4570-b53b-0ded067fd1c4",
      "Urgency": "Medium",
      "Category": "gerneral questions",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_13848300645",
      "ErrorCategory": "VNFM",
      "Comment": "Eu aliquip incididunt irure laborum duis laborum dolor ipsum eu amet fugiat. Voluptate dolore minim pariatur commodo laboris nulla non cupidatat. Minim ipsum esse deserunt exercitation qui amet sint nostrud labore non ullamco aliqua ullamco do. Nulla voluptate nostrud pariatur est nostrud proident ut minim adipisicing eiusmod. Esse duis cillum ea aute laborum culpa commodo proident dolore sint irure sint. Et irure duis in officia in dolor ullamco.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013975120",
      "createDate": "2018-05-20T06:43:34 +05:00",
      "caller_id": 8362682010,
      "affected_user": 8362682010,
      "JobId": "3f8f461a-69d3-46f1-b9fd-a026047db4d2",
      "Urgency": "Medium",
      "Category": "vmfmp issues",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_16124576211",
      "ErrorCategory": "NFVD Access-New acct",
      "Comment": "Ea officia Lorem eiusmod ad voluptate consectetur ut ut elit sint excepteur adipisicing ullamco sint. Dolor id irure veniam voluptate labore nostrud eu. Do consequat consectetur do magna veniam cupidatat eiusmod occaecat voluptate culpa ea. Incididunt aliqua proident adipisicing et exercitation duis non sunt commodo cupidatat. Occaecat incididunt est incididunt in mollit non cillum labore proident consectetur aute et in.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC012259366",
      "createDate": "2014-09-03T01:20:40 +05:00",
      "caller_id": 8234899721,
      "affected_user": 8234899721,
      "JobId": "0f72bc89-bc30-4f9d-9cbd-dec8d46aba0d",
      "Urgency": "Medium",
      "Category": "atlas issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_17462621568",
      "ErrorCategory": "NFVD UI",
      "Comment": "Duis ex nisi occaecat laboris minim minim ea laborum irure aliqua qui esse. Ullamco proident reprehenderit duis et amet est anim reprehenderit aute ad exercitation qui ad magna. Nostrud exercitation dolore nostrud reprehenderit nostrud magna do do consectetur dolore enim. Nostrud dolore qui magna incididunt nisi. Cupidatat occaecat aute esse commodo amet eu exercitation quis eu dolore elit velit consectetur.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013926065",
      "createDate": "2021-10-07T01:02:02 +05:00",
      "caller_id": 8380489165,
      "affected_user": 8380489165,
      "JobId": "52ca550e-5422-4388-9566-156742065e95",
      "Urgency": "High",
      "Category": "enhancement request",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_17133482038",
      "ErrorCategory": "NFVD UI",
      "Comment": "Fugiat culpa proident adipisicing esse qui voluptate Lorem ipsum. Commodo occaecat ex id enim id cillum deserunt non. Dolore cillum dolore id irure irure nulla tempor mollit. In adipisicing eiusmod voluptate proident ullamco eiusmod et sit deserunt magna nostrud aliqua consequat ut. Anim aliqua quis elit elit ullamco eu esse cillum fugiat magna voluptate. Dolor cillum dolore fugiat in magna elit id est veniam anim ex anim.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC012273027",
      "createDate": "2020-04-17T04:49:44 +05:00",
      "caller_id": 8991749035,
      "affected_user": 8991749035,
      "JobId": "303d1d1a-a162-4521-b3a4-c69b34c11c91",
      "Urgency": "Low",
      "Category": "atlas issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_14543208233",
      "ErrorCategory": "Error executing operation deploy",
      "Comment": "Non occaecat sit sunt consectetur. Anim do magna culpa tempor nulla veniam laborum incididunt. Elit eiusmod ad sunt aliqua pariatur ad ipsum. Anim elit elit reprehenderit amet qui cupidatat non anim.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013267640",
      "createDate": "2015-12-17T05:35:59 +06:00",
      "caller_id": 8719079700,
      "affected_user": 8719079700,
      "JobId": "1ce0bb27-9cae-45fa-88cf-653c119ea05d",
      "Urgency": "Low",
      "Category": "NFVD portal issues",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_17297841866",
      "ErrorCategory": "VNF Deploy/Upgrade Issue",
      "Comment": "Adipisicing est non qui officia et et enim sint reprehenderit. Mollit deserunt consequat nisi ullamco et proident. Do sint nisi nulla minim consequat minim duis elit ipsum. Exercitation et in amet aliqua aliqua irure anim deserunt sit duis. Excepteur eiusmod nulla cupidatat cupidatat incididunt nostrud irure reprehenderit labore sint dolore officia.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC012648315",
      "createDate": "2017-03-28T11:56:15 +05:00",
      "caller_id": 8510908665,
      "affected_user": 8510908665,
      "JobId": "a2fe0211-8450-4f58-9088-fda1c70ac019",
      "Urgency": "Medium",
      "Category": "vmfmp issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_15765597442",
      "ErrorCategory": "API-token",
      "Comment": "Sit commodo in laboris aute ut commodo sit esse irure. Tempor excepteur voluptate dolore magna ea anim consectetur nulla excepteur id cupidatat. Pariatur nisi sit occaecat proident proident occaecat esse culpa reprehenderit Lorem anim duis consequat.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC013385693",
      "createDate": "2018-10-14T12:06:38 +05:00",
      "caller_id": 8222549457,
      "affected_user": 8222549457,
      "JobId": "caab1baa-e743-46a6-9ce3-fa7324a3c0c2",
      "Urgency": "High",
      "Category": "alerting/side jobs",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_17842025163",
      "ErrorCategory": "NFVD Access-New acct",
      "Comment": "Sint tempor voluptate in tempor qui fugiat. Excepteur ex sit occaecat id commodo aliquip nulla nulla sunt enim nostrud aliquip. Nulla culpa pariatur laboris ex cillum minim anim sunt occaecat duis et est. Officia et et excepteur enim eu magna. Labore ea duis dolore enim et mollit exercitation. Occaecat non ipsum excepteur sint cupidatat consequat tempor cillum nulla enim.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC013985775",
      "createDate": "2020-10-27T12:05:43 +05:00",
      "caller_id": 8395537169,
      "affected_user": 8395537169,
      "JobId": "730345ad-fee9-45a9-9864-37fe078b5abc",
      "Urgency": "Low",
      "Category": "NFVD portal issues",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_15448087886",
      "ErrorCategory": "Error executing operation deploy",
      "Comment": "Deserunt cillum fugiat est deserunt occaecat minim cupidatat aliqua aliquip est labore est. Incididunt ut cillum anim velit ipsum consectetur pariatur pariatur officia. Sit proident laboris nulla esse Lorem fugiat ullamco reprehenderit id reprehenderit sint deserunt veniam. Ad adipisicing cupidatat duis dolor consectetur ullamco in culpa cupidatat est consequat eu ad. Dolore consequat duis eu consequat reprehenderit consequat veniam commodo ea. Ipsum ex excepteur quis ad Lorem.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013066240",
      "createDate": "2020-02-10T07:35:00 +06:00",
      "caller_id": 8607169543,
      "affected_user": 8607169543,
      "JobId": "36f28807-f4a0-4fb4-b4d5-109ffaca6dfb",
      "Urgency": "High",
      "Category": "atlas issues",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_14634245692",
      "ErrorCategory": "NFVD hierarchy-(DV/VDC/VNFG)",
      "Comment": "Enim anim elit cillum quis. Mollit duis ipsum velit dolor sint voluptate anim consequat amet quis. Reprehenderit minim non ea mollit labore velit. Ut minim sit magna culpa ipsum. Aute esse magna qui do aute ex elit. Ipsum aute duis nisi ea labore sunt eu exercitation commodo sint quis. Cupidatat quis Lorem esse velit dolor aliquip id occaecat cillum esse mollit sunt.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC012303206",
      "createDate": "2023-04-27T08:15:56 +05:00",
      "caller_id": 8576241767,
      "affected_user": 8576241767,
      "JobId": "0a9c74b4-c1b3-47fc-bec3-ce519c0d7115",
      "Urgency": "High",
      "Category": "enhancement request",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_14150647831",
      "ErrorCategory": "CNF Deploy/Upgrade Issue",
      "Comment": "Tempor tempor sit incididunt occaecat do esse ipsum aliqua. Ad ullamco nulla culpa aute. Voluptate ut deserunt aliqua proident veniam nisi magna cillum labore sunt velit.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC014036832",
      "createDate": "2022-11-28T10:06:13 +06:00",
      "caller_id": 8256781705,
      "affected_user": 8256781705,
      "JobId": "89bf89c8-d0b1-4410-8099-8d7e78885185",
      "Urgency": "Medium",
      "Category": "NFVD gui issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_16499724672",
      "ErrorCategory": "NFVD UI",
      "Comment": "Eiusmod culpa do esse sint id culpa et quis culpa anim reprehenderit occaecat occaecat consequat. Consectetur ex ea ad cupidatat. Dolor veniam dolore tempor nulla voluptate consectetur aliqua aute laborum irure.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC012390177",
      "createDate": "2018-03-20T05:12:43 +05:00",
      "caller_id": 8531427156,
      "affected_user": 8531427156,
      "JobId": "82bded2a-3e2c-4c69-ad7e-2656235425ed",
      "Urgency": "Medium",
      "Category": "enhancement request",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_14419631455",
      "ErrorCategory": "Onboarding-Kubeconfig connectivity",
      "Comment": "Ullamco anim elit reprehenderit ea deserunt ea ea aliqua occaecat ex. Anim culpa do adipisicing exercitation sunt pariatur occaecat consectetur. Minim ex occaecat proident ad aute non sunt eiusmod cillum officia incididunt ex. Lorem proident sunt amet esse et commodo magna. Commodo ut reprehenderit veniam voluptate nisi sit consequat ea amet ex.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC012648906",
      "createDate": "2020-02-26T09:26:06 +06:00",
      "caller_id": 8923319862,
      "affected_user": 8923319862,
      "JobId": "3358312a-c059-4b38-a7af-305c03278a96",
      "Urgency": "Medium",
      "Category": "onboarding issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_15632049578",
      "ErrorCategory": "Error executing operation deploy",
      "Comment": "Ut et non sint reprehenderit culpa ut consectetur occaecat proident minim ea. Cillum irure laborum enim laborum id veniam exercitation veniam magna. Reprehenderit aliquip consectetur exercitation sit culpa magna incididunt cillum adipisicing ut. Do nulla sunt tempor ad elit. Velit fugiat sunt ea duis. Eiusmod eu cillum sint ad enim consectetur laboris reprehenderit laboris anim id. Cillum voluptate consectetur laborum dolore veniam duis exercitation proident laboris mollit excepteur labore.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC012333487",
      "createDate": "2020-12-11T02:10:00 +06:00",
      "caller_id": 8215245826,
      "affected_user": 8215245826,
      "JobId": "f5bf56d2-3d6f-4a50-aee9-a36ce2eed2cd",
      "Urgency": "High",
      "Category": "enhancement request",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_15263508937",
      "ErrorCategory": "VNFM",
      "Comment": "Aute esse irure pariatur ipsum consequat consectetur Lorem incididunt duis. Voluptate cupidatat esse laborum do eiusmod culpa anim aliqua incididunt eu eiusmod exercitation duis commodo. Aliqua ea commodo et officia sint in occaecat. Aliquip tempor quis excepteur amet sunt aliquip Lorem.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC012514322",
      "createDate": "2021-08-21T01:21:27 +05:00",
      "caller_id": 8724976103,
      "affected_user": 8724976103,
      "JobId": "405e5cd7-d792-479f-85b1-9f863175d282",
      "Urgency": "High",
      "Category": "atlas issues",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_13660740378",
      "ErrorCategory": "CNF Deploy/Upgrade Issue",
      "Comment": "Elit pariatur mollit voluptate et Lorem esse incididunt mollit deserunt laborum aliquip quis nulla sit. Irure eiusmod tempor exercitation cupidatat Lorem Lorem veniam. Proident ipsum ea cupidatat dolore elit dolor ut amet velit Lorem cillum non. Deserunt ullamco adipisicing pariatur et velit cupidatat sit.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013391009",
      "createDate": "2021-11-20T12:34:49 +06:00",
      "caller_id": 8343898128,
      "affected_user": 8343898128,
      "JobId": "9d70ee29-b61d-4d7c-b9e5-b22c528f6b6b",
      "Urgency": "Low",
      "Category": "NFVD portal issues",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_16659936855",
      "ErrorCategory": "NFVD Access-New acct",
      "Comment": "Fugiat qui enim ut fugiat. Magna do mollit irure consectetur incididunt. Velit eu non fugiat do exercitation laboris in exercitation sunt nisi nisi. Incididunt non incididunt tempor laboris cupidatat officia. Anim nulla veniam proident cillum aute anim.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013948051",
      "createDate": "2024-03-01T04:58:32 +06:00",
      "caller_id": 8473827501,
      "affected_user": 8473827501,
      "JobId": "b8e14e37-5470-433c-be10-3ba037013076",
      "Urgency": "Low",
      "Category": "enhancement request",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_13848117040",
      "ErrorCategory": "API-token",
      "Comment": "Cupidatat officia reprehenderit sint do in anim officia qui eiusmod fugiat consectetur adipisicing nisi. Culpa non dolore est dolor minim enim mollit minim aute quis. Ullamco velit sint in nisi sit sunt laborum. Reprehenderit pariatur ut aliqua incididunt. Qui tempor cupidatat dolor esse nulla amet voluptate incididunt cillum ex. Fugiat proident eu cupidatat et consectetur aliqua laborum.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC013773462",
      "createDate": "2017-03-31T06:19:42 +05:00",
      "caller_id": 8871671626,
      "affected_user": 8871671626,
      "JobId": "3aab825e-cd58-4347-b41a-2055a3e3156e",
      "Urgency": "Low",
      "Category": "alerting/side jobs",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_17073757766",
      "ErrorCategory": "NFVD hierarchy-(DV/VDC/VNFG)",
      "Comment": "Labore pariatur ipsum nisi velit consequat nisi aliqua eu anim magna est minim aliqua elit. Reprehenderit mollit reprehenderit occaecat dolor ut nostrud dolor ut reprehenderit exercitation nostrud. Non fugiat minim do Lorem ex Lorem magna pariatur aliqua. Esse ut aute consequat cupidatat nulla dolor. Nulla ad cillum esse non irure cillum laborum cillum nisi exercitation aute quis. Veniam cillum sit nostrud ea irure aliquip occaecat.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC012832071",
      "createDate": "2022-10-02T09:21:07 +05:00",
      "caller_id": 8986932584,
      "affected_user": 8986932584,
      "JobId": "b0f4ec3c-d07b-409e-bee4-b536e3a65a24",
      "Urgency": "Medium",
      "Category": "vmfmp issues",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_13618253224",
      "ErrorCategory": "API-token",
      "Comment": "Aliquip sit elit anim dolore ex occaecat id dolore amet proident. Exercitation qui commodo culpa sint. Amet laboris dolor non sit ea adipisicing minim cupidatat sit enim occaecat ullamco eu. In nisi adipisicing id et veniam. Reprehenderit dolore aliqua labore duis. Nulla aliqua ad enim proident sit veniam mollit minim qui laboris duis nostrud occaecat aute. Cillum ipsum sint Lorem proident deserunt elit cillum excepteur elit.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013605769",
      "createDate": "2021-02-22T01:18:14 +06:00",
      "caller_id": 8813175333,
      "affected_user": 8813175333,
      "JobId": "fc1a2b24-d628-4526-af8e-65284018e020",
      "Urgency": "Medium",
      "Category": "gerneral questions",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_13705697930",
      "ErrorCategory": "Error executing operation deploy",
      "Comment": "Nostrud dolore aute qui pariatur ea cillum minim et ut dolor exercitation nulla pariatur. Aliquip labore proident culpa consectetur veniam. Dolor elit reprehenderit quis sunt fugiat duis duis ea consequat reprehenderit elit fugiat.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC013666233",
      "createDate": "2015-03-07T12:49:43 +06:00",
      "caller_id": 8665770364,
      "affected_user": 8665770364,
      "JobId": "8eca4db9-9554-4526-b5be-1a454bf3e9e2",
      "Urgency": "High",
      "Category": "enhancement request",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_14295855114",
      "ErrorCategory": "NFVD UI",
      "Comment": "Est ex nulla nulla ea culpa non consequat incididunt. Ipsum amet do esse labore magna commodo magna veniam proident ad minim esse duis incididunt. Ipsum sunt non ex magna proident cillum id laboris exercitation voluptate. Pariatur amet irure Lorem do deserunt sunt magna incididunt ex et. Mollit pariatur cupidatat laborum aliqua excepteur est minim ipsum incididunt nostrud culpa officia.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC012675124",
      "createDate": "2020-03-18T03:11:02 +05:00",
      "caller_id": 8937123996,
      "affected_user": 8937123996,
      "JobId": "f16b5096-e6af-432e-950c-6cd3b8f3215e",
      "Urgency": "High",
      "Category": "onboarding issues",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_17066169081",
      "ErrorCategory": "NFVD Access-New acct",
      "Comment": "Sunt officia reprehenderit non irure. Ut exercitation id nulla ullamco eu aliqua officia. Excepteur deserunt cillum nostrud est ea quis non enim proident ex laborum. Nisi dolor dolore anim fugiat.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC012340858",
      "createDate": "2016-01-31T11:47:17 +06:00",
      "caller_id": 8761599055,
      "affected_user": 8761599055,
      "JobId": "91e21ce7-d817-4ce4-859a-9027487380bb",
      "Urgency": "Medium",
      "Category": "gerneral questions",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_17062022267",
      "ErrorCategory": "VNFM",
      "Comment": "Sint mollit aliquip mollit sint magna adipisicing tempor. Pariatur reprehenderit quis pariatur consectetur aute ad. Veniam occaecat officia ex deserunt occaecat aliqua est.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC013092826",
      "createDate": "2020-04-20T06:59:50 +05:00",
      "caller_id": 8519767982,
      "affected_user": 8519767982,
      "JobId": "87e5676d-d3ff-484c-bc88-77c6912c8f78",
      "Urgency": "Medium",
      "Category": "vmfmp issues",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_16496811058",
      "ErrorCategory": "NFVD UI",
      "Comment": "Ad ex magna magna id minim. Culpa esse velit ea cillum. Do amet do consectetur mollit occaecat enim elit nostrud tempor aliquip sit consectetur. Quis laborum qui et commodo aliqua commodo irure dolore sint mollit cupidatat sint sint. Duis laborum aute exercitation ullamco irure enim.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC014010538",
      "createDate": "2015-08-30T10:58:39 +05:00",
      "caller_id": 8331055094,
      "affected_user": 8331055094,
      "JobId": "5eb1c972-0f4a-4b10-85d9-c1b839975916",
      "Urgency": "Low",
      "Category": "atlas issues",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_13878684717",
      "ErrorCategory": "NFVD UI",
      "Comment": "Elit anim duis velit proident. Eiusmod sit esse cupidatat fugiat duis. Id non amet duis proident cupidatat nostrud ipsum aliqua adipisicing ullamco commodo anim duis adipisicing. Eu proident velit in commodo amet occaecat proident in velit sint occaecat deserunt eu veniam. Proident enim sint amet excepteur eu anim aliqua. Consectetur mollit ipsum sit sit irure elit ipsum ipsum dolor consectetur aliqua. Lorem et aute ex laboris occaecat.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC014126686",
      "createDate": "2016-12-15T03:35:47 +06:00",
      "caller_id": 8124636264,
      "affected_user": 8124636264,
      "JobId": "5015cbf0-ff52-47cf-b917-bb47588ec069",
      "Urgency": "Medium",
      "Category": "gerneral questions",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_15927284030",
      "ErrorCategory": "CNF Deploy/Upgrade Issue",
      "Comment": "Cillum eiusmod adipisicing fugiat mollit duis. Duis ad cupidatat fugiat veniam. Ex est deserunt veniam adipisicing amet cillum tempor Lorem incididunt. Qui do minim proident eu mollit laboris est ex reprehenderit culpa exercitation officia. In duis ullamco commodo ullamco tempor est irure commodo dolor veniam elit. Irure aliqua ea ullamco qui. Deserunt sit qui sit mollit.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC012879107",
      "createDate": "2018-02-25T10:07:23 +06:00",
      "caller_id": 8509235881,
      "affected_user": 8509235881,
      "JobId": "7dcddc7d-19f6-42ed-824d-d3f8f5fe898b",
      "Urgency": "Low",
      "Category": "NFVD portal issues",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_16214154951",
      "ErrorCategory": "NFVD UI",
      "Comment": "Dolore culpa dolore laborum non esse quis et. Anim veniam qui tempor eu ad aliquip culpa nostrud aliquip. Adipisicing dolore ex est dolor incididunt dolore anim commodo officia reprehenderit excepteur. Consequat adipisicing quis Lorem irure veniam aute et reprehenderit ex magna proident sint. Sunt commodo eiusmod incididunt minim.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013686284",
      "createDate": "2018-01-09T07:26:23 +06:00",
      "caller_id": 8923699175,
      "affected_user": 8923699175,
      "JobId": "8fea0382-df22-4a5c-b7ea-c06dce4e3d90",
      "Urgency": "High",
      "Category": "atlas issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_14273199828",
      "ErrorCategory": "NFVD hierarchy-(DV/VDC/VNFG)",
      "Comment": "Anim pariatur occaecat et ea minim proident aliquip proident adipisicing tempor irure anim eiusmod. Quis ullamco magna cupidatat ullamco labore occaecat reprehenderit incididunt in ipsum et do aliqua. Qui cillum occaecat minim excepteur laborum. Sit culpa ea occaecat nostrud sit aute laboris dolor magna ad eu magna excepteur laborum. Velit veniam sit velit culpa ad irure exercitation veniam deserunt velit duis exercitation culpa.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013488597",
      "createDate": "2019-10-13T05:51:15 +05:00",
      "caller_id": 8497932658,
      "affected_user": 8497932658,
      "JobId": "af96319d-8214-4c63-a6a0-10917f2b6c53",
      "Urgency": "High",
      "Category": "gerneral questions",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_15667958598",
      "ErrorCategory": "VNFM",
      "Comment": "Reprehenderit sunt reprehenderit nostrud magna mollit dolore occaecat ipsum duis magna nostrud ullamco proident et. Elit consequat ut occaecat ea cillum aliqua. Ex veniam eu ea nostrud.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC012571788",
      "createDate": "2015-11-15T12:44:03 +06:00",
      "caller_id": 8820401375,
      "affected_user": 8820401375,
      "JobId": "101a8ce9-d5a4-4696-b900-473d3fd98e3f",
      "Urgency": "Medium",
      "Category": "NFVD portal issues",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_13679848992",
      "ErrorCategory": "NFVD hierarchy-(DV/VDC/VNFG)",
      "Comment": "Aliquip ad ea labore anim ad adipisicing do amet. Id cillum occaecat nulla amet. Do ea sunt proident eu eu proident ullamco esse deserunt.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC012170050",
      "createDate": "2023-05-08T05:02:08 +05:00",
      "caller_id": 8733160248,
      "affected_user": 8733160248,
      "JobId": "5eae8250-4828-4f37-aa4f-6c00af57e882",
      "Urgency": "High",
      "Category": "onboarding issues",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_18199238165",
      "ErrorCategory": "VNF Deploy/Upgrade Issue",
      "Comment": "Magna officia nisi elit fugiat sint eiusmod exercitation mollit officia duis pariatur elit commodo excepteur. Magna incididunt laborum eiusmod sint dolore veniam aute ullamco. Nulla veniam aute tempor sit irure aute qui dolor dolore labore.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC013683953",
      "createDate": "2016-08-03T05:57:44 +05:00",
      "caller_id": 8169095063,
      "affected_user": 8169095063,
      "JobId": "6edc4c40-f20f-48d6-bd09-ec994aba1a52",
      "Urgency": "High",
      "Category": "other",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_14819782484",
      "ErrorCategory": "NFVD Access-New acct",
      "Comment": "Adipisicing in in nisi sunt est consectetur adipisicing eiusmod. Tempor excepteur ut ex consectetur. Labore dolore minim ipsum ullamco ea irure. Dolor incididunt culpa eiusmod deserunt consequat commodo sint aliqua. Deserunt nisi do labore excepteur et tempor ea Lorem ex exercitation id consectetur id anim. Ipsum proident aliqua exercitation fugiat id amet nisi ad voluptate.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC012716545",
      "createDate": "2020-01-29T12:03:58 +06:00",
      "caller_id": 8967433069,
      "affected_user": 8967433069,
      "JobId": "6ccedd38-e46f-49cf-90d5-1bec85e9b4af",
      "Urgency": "Medium",
      "Category": "NFVD portal issues",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_18218633469",
      "ErrorCategory": "VNF Deploy/Upgrade Issue",
      "Comment": "Consequat enim laborum cillum qui aute anim eu excepteur magna duis labore. Voluptate proident sit esse do ad quis deserunt veniam. Amet ullamco excepteur minim velit. Non adipisicing reprehenderit et laboris aliquip in Lorem ad ea est sit. Culpa sunt anim magna quis.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC013294425",
      "createDate": "2020-09-08T05:35:57 +05:00",
      "caller_id": 8141713879,
      "affected_user": 8141713879,
      "JobId": "9cb8f274-a5d0-411c-b07c-9d1cfa0f08ee",
      "Urgency": "High",
      "Category": "onboarding issues",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_17368772766",
      "ErrorCategory": "Onboarding-Kubeconfig connectivity",
      "Comment": "Mollit dolore tempor id quis officia deserunt esse dolore laborum amet est occaecat ullamco nostrud. Dolor aliqua deserunt commodo anim qui Lorem magna incididunt do nostrud voluptate in sit. Et anim tempor consectetur est qui laboris laboris nisi. Nulla aliqua in aute consectetur magna excepteur. Officia id reprehenderit ex pariatur voluptate.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC012259128",
      "createDate": "2014-09-21T03:35:03 +05:00",
      "caller_id": 8883242808,
      "affected_user": 8883242808,
      "JobId": "aad70588-d680-459b-a376-b6ec16fafdd1",
      "Urgency": "High",
      "Category": "onboarding issues",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_14028046274",
      "ErrorCategory": "VNFM",
      "Comment": "Laborum voluptate nulla id dolor amet adipisicing commodo. Ipsum deserunt culpa ex do minim occaecat laboris et velit consequat enim do officia. Esse ad quis velit et non. Anim ullamco laborum cupidatat proident consectetur consectetur sit ex in consectetur adipisicing. Ex officia ea occaecat consectetur. Culpa aute ad irure officia non laboris deserunt.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC012324625",
      "createDate": "2024-06-12T08:13:59 +05:00",
      "caller_id": 8667585620,
      "affected_user": 8667585620,
      "JobId": "37f16edc-920e-4297-bc1e-24e04759a060",
      "Urgency": "Low",
      "Category": "NFVD gui issues",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_15403920735",
      "ErrorCategory": "VNF Deploy/Upgrade Issue",
      "Comment": "Excepteur nisi adipisicing adipisicing anim consectetur ad consequat cupidatat. Ad irure deserunt sit quis elit. Laboris tempor amet tempor Lorem incididunt elit adipisicing eiusmod anim occaecat adipisicing pariatur. Adipisicing eu deserunt cillum duis dolor irure nisi. Amet sunt exercitation ex do voluptate minim dolore culpa nulla ea quis nulla. Laborum nisi excepteur et sit culpa in mollit proident elit veniam.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC013455035",
      "createDate": "2022-12-16T02:46:43 +06:00",
      "caller_id": 8847338900,
      "affected_user": 8847338900,
      "JobId": "1a8087c4-435e-4951-b8b6-96173f3f56ae",
      "Urgency": "Medium",
      "Category": "NFVD portal issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_14345625453",
      "ErrorCategory": "CNF Deploy/Upgrade Issue",
      "Comment": "Officia tempor commodo amet adipisicing nisi ullamco fugiat nostrud magna do magna. Esse consequat commodo amet Lorem. Aliquip dolor do consectetur irure labore ipsum ad. Duis veniam excepteur aliquip nostrud occaecat consequat nisi culpa excepteur magna eiusmod. Labore in eiusmod Lorem ullamco. Fugiat Lorem deserunt do excepteur do.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC013500671",
      "createDate": "2019-11-01T11:54:10 +05:00",
      "caller_id": 8654090912,
      "affected_user": 8654090912,
      "JobId": "b4aaa56c-fe3b-48c9-9ab7-4094891bf0af",
      "Urgency": "High",
      "Category": "other",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_16670236866",
      "ErrorCategory": "CNF Deploy/Upgrade Issue",
      "Comment": "Id culpa pariatur ea cupidatat nisi in velit nostrud. Proident ea consectetur adipisicing ad consequat pariatur laborum minim dolor non et. Nisi enim fugiat laboris in fugiat ex quis.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC013342972",
      "createDate": "2023-07-08T03:01:11 +05:00",
      "caller_id": 8484359115,
      "affected_user": 8484359115,
      "JobId": "ee0f0f4e-2049-4843-816b-78b7c0450c6f",
      "Urgency": "High",
      "Category": "atlas issues",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_17430409101",
      "ErrorCategory": "VNF Deploy/Upgrade Issue",
      "Comment": "Commodo amet Lorem in ipsum. Cupidatat consequat cupidatat velit nostrud. Consectetur qui Lorem magna excepteur aute consequat duis cillum deserunt do enim.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013179361",
      "createDate": "2023-01-09T11:23:06 +06:00",
      "caller_id": 8411966047,
      "affected_user": 8411966047,
      "JobId": "3ed99dc2-df7f-48fd-aa14-219343af5443",
      "Urgency": "Low",
      "Category": "gerneral questions",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_15633243444",
      "ErrorCategory": "NFVD Access-New acct",
      "Comment": "Lorem aliqua nostrud qui magna tempor magna reprehenderit qui aliquip et mollit qui incididunt. Eiusmod voluptate anim anim velit amet. Nisi id aliqua anim qui nulla exercitation culpa enim ullamco eu in enim. Fugiat magna laboris minim cupidatat magna ut officia. Excepteur aliqua irure nostrud labore aliquip cupidatat Lorem sint labore fugiat elit enim.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC014149306",
      "createDate": "2022-03-13T09:05:48 +05:00",
      "caller_id": 8961328601,
      "affected_user": 8961328601,
      "JobId": "1f174704-a234-4d5f-8025-70e5f4d19124",
      "Urgency": "Medium",
      "Category": "atlas issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_14989828974",
      "ErrorCategory": "Onboarding-Kubeconfig connectivity",
      "Comment": "Eu quis ullamco laboris amet minim anim in laboris reprehenderit fugiat. Ea dolore commodo amet nulla. Lorem culpa sit occaecat elit tempor.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC012398011",
      "createDate": "2018-04-23T12:37:20 +05:00",
      "caller_id": 8838618300,
      "affected_user": 8838618300,
      "JobId": "03e415ac-297a-463f-9f30-3fb14eb285f7",
      "Urgency": "Medium",
      "Category": "NFVD gui issues",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_18216682287",
      "ErrorCategory": "Onboarding-Kubeconfig connectivity",
      "Comment": "Do commodo voluptate adipisicing aliqua do eu cupidatat sit. Pariatur irure ullamco fugiat in consectetur culpa voluptate cillum. Duis voluptate minim voluptate sit nostrud occaecat Lorem laborum dolor anim cupidatat deserunt irure Lorem. Amet ex tempor incididunt non enim Lorem ut cupidatat culpa qui commodo aliqua id. Sunt adipisicing nostrud cillum anim laboris.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013457518",
      "createDate": "2016-09-21T05:44:53 +05:00",
      "caller_id": 8571291553,
      "affected_user": 8571291553,
      "JobId": "9bd4286f-d46d-453c-bda6-ef5781db7a2f",
      "Urgency": "Medium",
      "Category": "enhancement request",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_14857563682",
      "ErrorCategory": "NFVD UI",
      "Comment": "Velit et anim sint cillum adipisicing irure consectetur. Anim eu id fugiat do do sunt. Culpa et est cupidatat ipsum amet esse labore.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC013116308",
      "createDate": "2017-12-05T10:36:03 +06:00",
      "caller_id": 8952224221,
      "affected_user": 8952224221,
      "JobId": "d761dcd1-4824-40a5-a2b5-f3b3fa251667",
      "Urgency": "Low",
      "Category": "alerting/side jobs",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_18417930792",
      "ErrorCategory": "NFVD Access-New acct",
      "Comment": "Ex dolor id esse cupidatat nisi consectetur velit laborum. Dolore sint occaecat aute ullamco adipisicing ipsum aute eu laborum laborum. Veniam magna qui eiusmod consectetur velit laborum labore magna anim labore occaecat in labore proident. Deserunt consequat irure ut ad culpa esse deserunt consequat minim. Ea ipsum excepteur adipisicing dolore ullamco consequat.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC012563680",
      "createDate": "2017-09-12T04:33:12 +05:00",
      "caller_id": 8154973736,
      "affected_user": 8154973736,
      "JobId": "9ea13b7e-bfa6-48a7-a213-54d2e9e26157",
      "Urgency": "Medium",
      "Category": "other",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_17522882124",
      "ErrorCategory": "Error executing operation deploy",
      "Comment": "Deserunt esse dolor occaecat commodo veniam anim. Ex laborum minim laboris quis incididunt veniam velit veniam. Eiusmod est ipsum dolore anim in commodo mollit anim ad magna est. Enim excepteur magna anim incididunt deserunt. Cupidatat magna consectetur non sunt sint qui mollit culpa nostrud est nulla id amet quis.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC013489093",
      "createDate": "2017-06-07T02:33:53 +05:00",
      "caller_id": 8622861955,
      "affected_user": 8622861955,
      "JobId": "f3fe6a25-2867-4e4c-8eed-395b4b6c2866",
      "Urgency": "Low",
      "Category": "NFVD portal issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_17994136509",
      "ErrorCategory": "Error executing operation deploy",
      "Comment": "Ullamco cillum culpa enim quis cillum. Labore voluptate velit qui consequat duis. Tempor proident aliquip ad Lorem ut ea dolore laboris veniam et. Irure commodo ipsum laborum in aliqua laborum est sunt aute consectetur.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013007837",
      "createDate": "2021-01-31T02:36:51 +06:00",
      "caller_id": 8691710958,
      "affected_user": 8691710958,
      "JobId": "761c68ec-b1d3-459c-a8b7-df5d6d53bbf7",
      "Urgency": "Medium",
      "Category": "gerneral questions",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_17526776941",
      "ErrorCategory": "NFVD hierarchy-(DV/VDC/VNFG)",
      "Comment": "Laboris eu minim excepteur do magna esse ea. Aliquip laborum ullamco duis proident fugiat mollit ea Lorem fugiat est nostrud aliquip est. Duis occaecat cillum consequat duis. Nulla dolore exercitation mollit incididunt laboris anim minim dolore.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC012932021",
      "createDate": "2021-09-21T03:48:48 +05:00",
      "caller_id": 8758939081,
      "affected_user": 8758939081,
      "JobId": "96d402a9-7c80-43be-aa65-a017214a4f90",
      "Urgency": "High",
      "Category": "NFVD gui issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_16766747549",
      "ErrorCategory": "CNF Deploy/Upgrade Issue",
      "Comment": "Eu culpa consectetur elit Lorem mollit duis nisi tempor laborum reprehenderit in. Eu quis et elit cillum Lorem dolor consectetur. Consequat eiusmod incididunt officia ex cillum ullamco id nisi. Ullamco aliquip cupidatat eu amet cupidatat consectetur aliqua tempor eiusmod consequat culpa. Sint qui consectetur id aliqua nisi ex. Proident anim in Lorem incididunt ex Lorem duis voluptate aliqua laborum non ea laboris adipisicing.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC012802786",
      "createDate": "2020-09-21T07:23:08 +05:00",
      "caller_id": 8134619361,
      "affected_user": 8134619361,
      "JobId": "f94e6d1b-455a-4191-9dbc-8c15df2dd531",
      "Urgency": "Medium",
      "Category": "vmfmp issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_16254692484",
      "ErrorCategory": "CNF Deploy/Upgrade Issue",
      "Comment": "Commodo ullamco do est consequat qui quis velit esse nostrud dolor cillum sit qui mollit. Aliqua esse in nulla laborum voluptate reprehenderit mollit duis Lorem officia deserunt. Exercitation voluptate duis enim proident duis voluptate.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013637997",
      "createDate": "2019-05-05T08:20:37 +05:00",
      "caller_id": 8335846896,
      "affected_user": 8335846896,
      "JobId": "8c2672c1-667f-4f61-9927-3fc0655afe21",
      "Urgency": "High",
      "Category": "NFVD gui issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_14503351987",
      "ErrorCategory": "VNF Deploy/Upgrade Issue",
      "Comment": "Adipisicing aliqua nostrud excepteur cillum esse nisi incididunt aliqua quis ut ex culpa. Eiusmod officia sunt fugiat elit aute dolor aliquip excepteur. Ipsum labore ea eiusmod excepteur non enim nisi labore in proident.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC014014277",
      "createDate": "2021-12-11T03:06:32 +06:00",
      "caller_id": 8350445217,
      "affected_user": 8350445217,
      "JobId": "f388ec53-3324-4caa-b9fc-d03a503dde8c",
      "Urgency": "High",
      "Category": "alerting/side jobs",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_14611423849",
      "ErrorCategory": "NFVD Access-New acct",
      "Comment": "Irure Lorem consequat sunt esse mollit nisi cillum cupidatat cupidatat nulla. In amet aliqua incididunt nulla adipisicing sunt ullamco laboris pariatur cillum quis irure nulla. Proident eiusmod Lorem tempor sunt laboris deserunt eu officia aliqua. Irure ea non nisi id culpa amet.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013349970",
      "createDate": "2020-06-23T07:07:56 +05:00",
      "caller_id": 8659895541,
      "affected_user": 8659895541,
      "JobId": "11e68b7d-52fa-486d-9536-4714feef4d26",
      "Urgency": "Medium",
      "Category": "NFVD gui issues",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_13798509563",
      "ErrorCategory": "Onboarding-Kubeconfig connectivity",
      "Comment": "Proident quis laboris deserunt elit irure sunt tempor deserunt ad duis eiusmod sint nisi. Est pariatur ut veniam in officia amet aute et labore. Dolore non commodo nisi culpa ex elit. Lorem sunt proident sit consectetur labore proident cupidatat esse ipsum aliqua consectetur.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC012415875",
      "createDate": "2017-03-22T02:32:58 +05:00",
      "caller_id": 8741681737,
      "affected_user": 8741681737,
      "JobId": "701bce80-5426-4a2a-8414-8f8427881691",
      "Urgency": "Low",
      "Category": "NFVD gui issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_17246943790",
      "ErrorCategory": "VNFM",
      "Comment": "Consectetur quis non sit ea aliquip. Qui amet sint commodo anim laboris quis consequat laboris Lorem. Proident commodo aute laboris enim adipisicing velit elit laboris quis pariatur veniam. Ad ullamco proident enim anim tempor. Cillum eiusmod sunt ex consectetur.\r\n",
      "Organization": "VNF"
    },
    {
      "inc_number": "INC013963527",
      "createDate": "2022-07-07T07:28:46 +05:00",
      "caller_id": 8929323833,
      "affected_user": 8929323833,
      "JobId": "8da3b422-4100-47c5-ae77-587b102f302b",
      "Urgency": "Medium",
      "Category": "atlas issues",
      "Vendor": "Samsung",
      "DataCenterCLLI": "USTXELSSVCPFE_16366408391",
      "ErrorCategory": "VNF Deploy/Upgrade Issue",
      "Comment": "Labore quis sint veniam esse mollit. Proident velit reprehenderit incididunt labore. Eu labore ut aliqua sunt ullamco velit Lorem.\r\n",
      "Organization": "CNF"
    },
    {
      "inc_number": "INC013216639",
      "createDate": "2019-07-12T11:08:23 +05:00",
      "caller_id": 8278122656,
      "affected_user": 8278122656,
      "JobId": "c6fbf225-627c-4feb-8fe4-0640719655be",
      "Urgency": "Medium",
      "Category": "onboarding issues",
      "Vendor": "None",
      "DataCenterCLLI": "USTXELSSVCPFE_14374988343",
      "ErrorCategory": "VNFM",
      "Comment": "Ullamco sit sunt pariatur dolor voluptate consequat commodo ipsum. Consectetur labore elit minim ut veniam deserunt eu reprehenderit excepteur. Occaecat sunt ullamco incididunt magna eiusmod laboris. Mollit voluptate aliquip anim dolore exercitation nulla irure non ex mollit. Ex pariatur amet sunt incididunt sunt nisi incididunt laboris cupidatat.\r\n",
      "Organization": "ORG"
    },
    {
      "inc_number": "INC012341743",
      "createDate": "2020-04-30T02:32:00 +05:00",
      "caller_id": 8126870180,
      "affected_user": 8126870180,
      "JobId": "c5368a0e-d184-4947-be03-c1d7caf463b6",
      "Urgency": "Low",
      "Category": "vmfmp issues",
      "Vendor": "Ericsson",
      "DataCenterCLLI": "USTXELSSVCPFE_16327764812",
      "ErrorCategory": "VNF Deploy/Upgrade Issue",
      "Comment": "Ex enim cillum culpa consequat in reprehenderit eiusmod proident veniam ullamco sit anim pariatur esse. Voluptate ex exercitation tempor labore aute aute voluptate nostrud ipsum cupidatat do reprehenderit cupidatat velit. Excepteur amet quis enim ut do exercitation duis anim cupidatat. Quis est nulla sint pariatur labore veniam quis Lorem cillum Lorem. Esse duis adipisicing eu ad. Cillum elit eu sit ea ea qui.\r\n",
      "Organization": "ORG"
    }
  ];

  app.get("/api/slack-issues", async (req, res) => {

    
    res.json(data);
  });

  app.get("/api/slack-issues-by-Error-Category", async (req, res) => {
    let issues = data;

    res.json(data);
  });

  app.get("/api/slack-issues-by-category", async (req, res) => {
    let issues = data;

    res.json(data);
  });

  app.get("/api/slack-issues-by-Urgency", async (req, res) => {
    let issues = data;

    res.json(data);
  });

  app.get("/api/slack-issues-by-Vendor", async (req, res) => {
    let issues = data;

    res.json(data);
  });

  app.get("/api/slack-issues-by-Organization", async (req, res) => {
    let issues = data;

    res.json(data);
  });

  app.get("/api/slack-issues-by-createDate", async (req, res) => {
    let issues = data;

    res.json(data);
    console.log(res);
  });

};